import test from'node:test';import assert from'node:assert/strict';import{DFWorkflow}from'../src/backend/dfWorkflow.js';import{MemoryRepository}from'../src/backend/memoryRepository.js';
const profiles=[{user_id:'sdo',display_name:'SDO',application_role:'SDO',active:true},{user_id:'a',display_name:'A',application_role:'SECTION_USER',assigned_section_id:'A',active:true},{user_id:'b',display_name:'B',application_role:'SECTION_USER',assigned_section_id:'B',active:true},{user_id:'lia',display_name:'L',application_role:'LIAISON',active:true},{user_id:'co',display_name:'CO',application_role:'CO',active:true}];const sections=[{id:'A',acronym:'A',active:true},{id:'B',acronym:'B',active:true}];const personnel=[{id:'pa',section_id:'A',active:true}];
function setup(status='DRAFT',extra={}){const df={id:'df',section_id:'A',version:5,revision_number:0,status,requesting_personnel_id:'pa',purpose:'Purpose',activity_requirement:'Activity',date_needed:'2026-08-20',fund_source:'MOOE',df_category:'OPS',requested_amount:1000,payment_mode:'Cash',justification:'Needed',original_receipt_status:'NOT_RECEIVED',fur_status:'NOT_RECEIVED',verification_status:'PENDING',...extra};const repo=new MemoryRepository({profiles:structuredClone(profiles),sections,personnel,dfs:[df]});return{repo,w:new DFWorkflow(repo)}}
const rejects=(promise,status)=>assert.rejects(promise,e=>e.status===status);
test('cross-section access is forbidden and role injection ignored',async()=>{const{w,repo}=setup();await rejects(Promise.resolve().then(()=>w.updateDraft('b','df',5,{role:'SDO',status:'CO_APPROVED'})),403);assert.equal(repo.df('df').status,'DRAFT')});
test('generic draft update ignores protected status',()=>{const{w}=setup();const d=w.updateDraft('a','df',5,{status:'CO_APPROVED',approved_amount:999,purpose:'Changed'});assert.equal(d.status,'DRAFT');assert.equal(d.approved_amount,undefined);assert.equal(d.purpose,'Changed')});
test('stale version returns 409',async()=>{const{w}=setup();w.updateDraft('a','df',5,{purpose:'A'});await rejects(Promise.resolve().then(()=>w.updateDraft('a','df',5,{purpose:'B'})),409)});
test('workflow bypass and terminal mutation rejected',async()=>{let x=setup();await rejects(Promise.resolve().then(()=>x.w.transition('sdo','df',5,'RELEASE',{amount:1})),409);x=setup('COMPLETED');await rejects(Promise.resolve().then(()=>x.w.updateDraft('a','df',5,{purpose:'x'})),409)});
test('partial approval is valid, approval above request is rejected',async()=>{let x=setup('FOR_CO_DECISION');let d=x.w.transition('co','df',5,'CO_DECISION',{decision:'APPROVED',approved_amount:500});assert.equal(d.approved_amount,500);x=setup('FOR_CO_DECISION');await rejects(Promise.resolve().then(()=>x.w.transition('co','df',5,'CO_DECISION',{decision:'APPROVED',approved_amount:1001})),422)});
test('release above approval rejected and double release permits one',async()=>{const x=setup('CO_APPROVED',{approved_amount:500});await rejects(Promise.resolve().then(()=>x.w.transition('sdo','df',5,'RELEASE',{amount:501})),422);const d=x.w.transition('sdo','df',5,'RELEASE',{amount:100});assert.equal(d.status,'FUND_RELEASED');await rejects(Promise.resolve().then(()=>x.w.transition('sdo','df',5,'RELEASE',{amount:100})),409)});
test('return above unused rejected; partial requires remarks and only one transaction',async()=>{let x=setup('UTILIZATION_RECORDED',{released_amount:100,utilized_amount:50});await rejects(Promise.resolve().then(()=>x.w.transition('a','df',5,'RETURN_FUNDS',{amount:51})),422);await rejects(Promise.resolve().then(()=>x.w.transition('a','df',5,'RETURN_FUNDS',{amount:25})),422);const d=x.w.transition('a','df',5,'RETURN_FUNDS',{amount:25,remarks:'Authorized variance'});assert.equal(d.returned_amount,25);await rejects(Promise.resolve().then(()=>x.w.transition('a','df',6,'RETURN_FUNDS',{amount:25,remarks:'again'})),409)});
test('SDO return confirmation ignores supplied amount and locks persisted return',()=>{const{w}=setup('UTILIZATION_RECORDED',{released_amount:100,utilized_amount:50,returned_amount:25,return_date:'date'});const d=w.transition('sdo','df',5,'CONFIRM_RETURN',{amount:20});assert.equal(d.sdo_return_confirmed_amount,25)});
test('reimbursement cannot exceed obligation or recorded amount',async()=>{let x=setup('UTILIZATION_RECORDED',{released_amount:100,utilized_amount:125});await rejects(Promise.resolve().then(()=>x.w.transition('sdo','df',5,'REIMBURSE',{amount:26})),422);let d=x.w.transition('sdo','df',5,'REIMBURSE',{amount:25});assert.equal(d.reimbursed_amount,25);await rejects(Promise.resolve().then(()=>x.w.transition('a','df',6,'CONFIRM_REIMBURSEMENT',{amount:26})),422)});
test('verification requires documents and reconciliation then completes immutably',async()=>{const x=setup('UTILIZATION_RECORDED',{released_amount:100,utilized_amount:100});await rejects(Promise.resolve().then(()=>x.w.transition('sdo','df',5,'VERIFY')),422);x.w.transition('sdo','df',5,'RECEIVE_RECEIPT');x.w.transition('sdo','df',6,'RECEIVE_FUR');const d=x.w.transition('sdo','df',7,'VERIFY');assert.equal(d.status,'COMPLETED');assert.equal(d.verification_status,'VERIFIED');await rejects(Promise.resolve().then(()=>x.w.transition('sdo','df',8,'VERIFY')),409)});
test('submission allocates stable reference and audit entries',()=>{const{w,repo}=setup();let d=w.submit('a','df',5);assert.match(d.reference_number,/^DF-A-\d{4}-0001$/);assert.equal(d.version,6);assert.equal(repo.actions.at(-1).action,'SUBMIT')});
