export const ROLES = Object.freeze({ SDO:'SDO', SECTION_USER:'SECTION_USER', LIAISON:'LIAISON', CO:'CO', ADMIN:'ADMIN' });
export const STATUS = Object.freeze({ DRAFT:'DRAFT', SUBMITTED_TO_SDO:'SUBMITTED_TO_SDO', UNDER_SDO_REVIEW:'UNDER_SDO_REVIEW', SENT_TO_CO:'SENT_TO_CO', FOR_CO_DECISION:'FOR_CO_DECISION', CO_APPROVED:'CO_APPROVED', CO_REJECTED:'CO_REJECTED', RETURNED_FOR_REVISION:'RETURNED_FOR_REVISION', FUND_RELEASED:'FUND_RELEASED', UTILIZATION_RECORDED:'UTILIZATION_RECORDED', COMPLETED:'COMPLETED' });
export const TERMINAL = new Set([STATUS.CO_REJECTED, STATUS.COMPLETED]);
export const DOCUMENT_STATUS = Object.freeze({ NOT_RECEIVED:'NOT_RECEIVED', RECEIVED:'RECEIVED' });
