import { DOCUMENT_STATUS, ROLES, STATUS, TERMINAL } from '../domain/constants.js';
import { canComplete, getOverutilizedAmount, getUnutilizedAmount } from '../domain/financial.js';
import { WorkflowError } from './errors.js';
const now=()=>new Date().toISOString(); const finitePositive=(v,label)=>{const n=Number(v);if(!Number.isFinite(n)||n<=0)throw new WorkflowError(422,`${label} must be greater than zero.`);return n};
const required=['requesting_personnel_id','purpose','activity_requirement','date_needed','fund_source','df_category','requested_amount','payment_mode','justification'];
export class DFWorkflow {
 constructor(repo){this.repo=repo}
 actor(userId){const p=this.repo.profile(userId);if(!p)throw new WorkflowError(401,'Authenticated account has no trusted UserProfile.');if(!p.active)throw new WorkflowError(403,'Your account is inactive.');return p}
 access(a,df){if(a.application_role===ROLES.SECTION_USER&&a.assigned_section_id!==df.section_id)throw new WorkflowError(403,"You cannot access another Section's DF.")}
 role(a,...roles){if(!roles.includes(a.application_role))throw new WorkflowError(403,'Your trusted role is not authorized for this action.')}
 load(userId,id,expected){const a=this.actor(userId),stored=this.repo.df(id),df=stored&&structuredClone(stored);if(!df)throw new WorkflowError(404,'DF not found.');this.access(a,df);if(expected!==df.version)throw new WorkflowError(409,'DF was modified by another user. Refresh before continuing.');if(TERMINAL.has(df.status))throw new WorkflowError(409,'Terminal DFs cannot be modified.');return {a,df,before:structuredClone(df)}}
 commit(a,before,df,action,remarks='',old_values={},new_values={}){df.version=before.version+1;df.updated_date=now();return this.repo.transaction(()=>{if(!this.repo.save(df,before.version))throw new WorkflowError(409,'DF was modified by another user. Refresh before continuing.');this.repo.audit({id:crypto.randomUUID(),df_id:df.id,reference_number:df.reference_number||'',action,from_status:before.status,to_status:df.status,user_id:a.user_id,user_name:a.display_name,role:a.application_role,remarks,old_values,new_values,revision_number:df.revision_number,timestamp:now()});return structuredClone(df)})}
 validatePersonnel(df){const p=this.repo.person(df.requesting_personnel_id);if(!p||!p.active||p.section_id!==df.section_id)throw new WorkflowError(422,"Requesting Personnel must be active and belong to the DF's Section.")}
 createDraft(userId,data){const a=this.actor(userId);this.role(a,ROLES.SDO,ROLES.SECTION_USER);const sectionId=a.application_role===ROLES.SECTION_USER?a.assigned_section_id:data.originating_section_id;if(!sectionId)throw new WorkflowError(422,'An originating Section is required.');if(!this.repo.section(sectionId)?.active)throw new WorkflowError(422,'The selected Section is inactive or missing.');const df={id:crypto.randomUUID(),reference_number:null,section_id:sectionId,created_by_role:a.application_role,created_date:now(),updated_date:now(),version:0,revision_number:0,status:STATUS.DRAFT,original_receipt_status:DOCUMENT_STATUS.NOT_RECEIVED,fur_status:DOCUMENT_STATUS.NOT_RECEIVED,verification_status:'PENDING',return_status:'NONE',reimbursement_status:'NONE',...Object.fromEntries(['requesting_personnel_id','purpose','activity_requirement','date_needed','fund_source','df_category','requested_amount','payment_mode','payee','justification','remarks'].map(k=>[k,data[k]??'']))};return this.repo.transaction(()=>{if(!this.repo.save(df))throw new WorkflowError(409,'DF could not be created.');this.repo.audit({id:crypto.randomUUID(),df_id:df.id,reference_number:null,action:'CREATE',from_status:null,to_status:df.status,user_id:a.user_id,user_name:a.display_name,role:a.application_role,revision_number:0,timestamp:now()});return structuredClone(df)})}
 updateDraft(userId,id,expected,data){const {a,df,before}=this.load(userId,id,expected);if(![STATUS.DRAFT,STATUS.RETURNED_FOR_REVISION].includes(df.status))throw new WorkflowError(409,'Only draft or returned records can be edited.');this.role(a,ROLES.SDO,ROLES.SECTION_USER);const allowed=['requesting_personnel_id','purpose','activity_requirement','date_needed','fund_source','df_category','requested_amount','payment_mode','payee','justification','remarks'];allowed.forEach(k=>{if(k in data)df[k]=data[k]});return this.commit(a,before,df,'UPDATE_DRAFT')}
 submit(userId,id,expected){const {a,df,before}=this.load(userId,id,expected);this.role(a,ROLES.SDO,ROLES.SECTION_USER);if(![STATUS.DRAFT,STATUS.RETURNED_FOR_REVISION].includes(df.status))throw new WorkflowError(409,'DF cannot be submitted from its current status.');for(const k of required)if(df[k]===null||df[k]===undefined||df[k]==='')throw new WorkflowError(422,`Missing required field: ${k}.`);df.requested_amount=finitePositive(df.requested_amount,'Requested Amount');this.validatePersonnel(df);if(!df.reference_number){const section=this.repo.section(df.section_id);const year=new Date().toLocaleString('en-US',{timeZone:'Asia/Manila',year:'numeric'});df.reference_number=`DF-${section.acronym}-${year}-${String(this.repo.nextSequence(`${section.id}:${year}`)).padStart(4,'0')}`}if(df.status===STATUS.RETURNED_FOR_REVISION)df.revision_number++;df.status=STATUS.SUBMITTED_TO_SDO;df.submitted_date=now();return this.commit(a,before,df,df.revision_number?'REVISION_RESUBMIT':'SUBMIT')}
 transition(userId,id,expected,action,payload={}){const {a,df,before}=this.load(userId,id,expected);let oldValues={},newValues={};const expect=(s)=>{if(df.status!==s)throw new WorkflowError(409,`Action requires ${s}; current status is ${df.status}.`)};
  if(action==='START_REVIEW'){this.role(a,ROLES.SDO);expect(STATUS.SUBMITTED_TO_SDO);df.status=STATUS.UNDER_SDO_REVIEW;df.sdo_review_date=now()}
  else if(action==='CHANGE_FUND_SOURCE'){this.role(a,ROLES.SDO);expect(STATUS.UNDER_SDO_REVIEW);if(!payload.fund_source||!payload.reason)throw new WorkflowError(422,'New fund source and reason are required.');df.original_fund_source||=df.fund_source;df.fund_source=payload.fund_source;df.fund_source_change_reason=payload.reason;df.fund_source_changed_date=now()}
  else if(action==='SEND_TO_CO'){this.role(a,ROLES.SDO);expect(STATUS.UNDER_SDO_REVIEW);df.status=STATUS.SENT_TO_CO}
  else if(action==='COORDINATE'){this.role(a,ROLES.LIAISON);expect(STATUS.SENT_TO_CO);df.status=STATUS.FOR_CO_DECISION}
  else if(action==='CO_DECISION'){this.role(a,ROLES.CO,ROLES.LIAISON);expect(STATUS.FOR_CO_DECISION);let co=a;if(a.application_role===ROLES.LIAISON){co=this.repo.profile(payload.co_user_id);if(!co?.active||co.application_role!==ROLES.CO)throw new WorkflowError(422,'Select an active trusted CO profile.')}const decision=payload.decision;if(!['APPROVED','REJECTED','RETURNED_FOR_REVISION'].includes(decision))throw new WorkflowError(422,'Invalid CO decision.');if(decision==='APPROVED'){const approved=finitePositive(payload.approved_amount,'Approved Amount');if(approved>Number(df.requested_amount))throw new WorkflowError(422,'Approved Amount cannot exceed Requested Amount.');df.approved_amount=approved;df.status=STATUS.CO_APPROVED}else{if(!payload.remarks)throw new WorkflowError(422,'CO remarks are required.');df.status=decision==='REJECTED'?STATUS.CO_REJECTED:STATUS.RETURNED_FOR_REVISION}df.co_decision=decision;df.co_remarks=payload.remarks||'';df.decision_by_id=co.user_id;df.decision_by_name=co.display_name;df.recorded_by_id=a.user_id;df.recorded_by_name=a.display_name;df.decision_date=now();df.co_decision_history=[...(df.co_decision_history||[]),{decision,decision_by_id:co.user_id,recorded_by_id:a.user_id,date:now(),remarks:payload.remarks||'',approved_amount:df.approved_amount||null}]}
  else if(action==='RELEASE'){this.role(a,ROLES.SDO);expect(STATUS.CO_APPROVED);const n=finitePositive(payload.amount,'Released Amount');if(n>Number(df.approved_amount))throw new WorkflowError(422,'Released Amount cannot exceed CO Approved Amount.');df.released_amount=n;df.release_date=now();df.status=STATUS.FUND_RELEASED}
  else if(action==='UTILIZE'){this.role(a,ROLES.SECTION_USER);expect(STATUS.FUND_RELEASED);const n=finitePositive(payload.amount,'Utilized Amount');df.utilized_amount=n;df.utilization_date=now();df.status=STATUS.UTILIZATION_RECORDED}
  else if(action==='RETURN_FUNDS'){this.role(a,ROLES.SECTION_USER);expect(STATUS.UTILIZATION_RECORDED);if(df.return_date)throw new WorkflowError(409,'A return transaction already exists. Use correction workflow.');const unused=getUnutilizedAmount(df),n=finitePositive(payload.amount,'Returned Amount');if(n>unused)throw new WorkflowError(422,`Returned Amount cannot exceed unused funds.`);if(n<unused&&!payload.remarks)throw new WorkflowError(422,'Remarks are required for a partial return.');df.returned_amount=n;df.return_remarks=payload.remarks||'';df.return_date=now();df.return_status='SUBMITTED'}
  else if(action==='CORRECT_RETURN'){this.role(a,ROLES.SECTION_USER);expect(STATUS.UTILIZATION_RECORDED);if(!df.return_date)throw new WorkflowError(409,'No return transaction exists to correct.');if(df.sdo_return_confirmation_date)throw new WorkflowError(409,'A confirmed return cannot be corrected.');const unused=getUnutilizedAmount(df),n=finitePositive(payload.amount,'Corrected Returned Amount');if(n>unused)throw new WorkflowError(422,'Corrected Returned Amount cannot exceed unused funds.');if(!payload.remarks)throw new WorkflowError(422,'Correction remarks are required.');const oldAmount=df.returned_amount;df.returned_amount=n;df.return_remarks=payload.remarks;df.return_corrected_date=now();df.return_status='CORRECTED';oldValues={returned_amount:oldAmount};newValues={returned_amount:n}}
  else if(action==='CONFIRM_RETURN'){this.role(a,ROLES.SDO);expect(STATUS.UTILIZATION_RECORDED);if(!df.return_date)throw new WorkflowError(409,'No Section return exists.');if(df.sdo_return_confirmation_date)throw new WorkflowError(409,'Return is already confirmed.');df.sdo_return_confirmed_amount=Number(df.returned_amount);df.sdo_return_confirmation_date=now();df.return_status='CONFIRMED'}
  else if(action==='ACCEPT_PARTIAL_RETURN'){this.role(a,ROLES.SDO);expect(STATUS.UTILIZATION_RECORDED);if(!df.sdo_return_confirmation_date||Number(df.returned_amount)>=getUnutilizedAmount(df)||!payload.remarks)throw new WorkflowError(422,'A confirmed partial return and acceptance remarks are required.');df.partial_return_exception_status='ACCEPTED';df.partial_return_exception_remarks=payload.remarks}
  else if(action==='REIMBURSE'){this.role(a,ROLES.SDO);expect(STATUS.UTILIZATION_RECORDED);const obligation=getOverutilizedAmount(df),n=finitePositive(payload.amount,'Reimbursement');if(Number(df.reimbursed_amount||0)+n>obligation)throw new WorkflowError(422,'Reimbursement cannot exceed remaining obligation.');df.reimbursed_amount=Number(df.reimbursed_amount||0)+n;df.reimbursement_status='RECORDED';df.reimbursement_date=now()}
  else if(action==='CONFIRM_REIMBURSEMENT'){this.role(a,ROLES.SECTION_USER);expect(STATUS.UTILIZATION_RECORDED);const n=finitePositive(payload.amount,'Confirmation');if(Number(df.section_reimbursement_confirmed_amount||0)+n>Number(df.reimbursed_amount||0))throw new WorkflowError(422,'Confirmation cannot exceed recorded reimbursement.');df.section_reimbursement_confirmed_amount=Number(df.section_reimbursement_confirmed_amount||0)+n;df.section_reimbursement_confirmation_date=now()}
  else if(action==='RECEIVE_RECEIPT'||action==='RECEIVE_FUR'){this.role(a,ROLES.SDO);expect(STATUS.UTILIZATION_RECORDED);const prefix=action==='RECEIVE_RECEIPT'?'original_receipt':'fur';if(df[`${prefix}_status`]==='RECEIVED')throw new WorkflowError(409,'Document was already received.');df[`${prefix}_status`]='RECEIVED';df[`${prefix}_received_date`]=now();df[`${prefix}_received_by_id`]=a.user_id;df[`${prefix}_received_by_name`]=a.display_name}
  else if(action==='VERIFY'){this.role(a,ROLES.SDO);expect(STATUS.UTILIZATION_RECORDED);if(!canComplete(df))throw new WorkflowError(422,'Original Receipt, FUR, and complete financial reconciliation are required before final verification.');df.verification_status='VERIFIED';df.verification_date=now();df.verified_by_id=a.user_id;df.verified_by_name=a.display_name;df.status=STATUS.COMPLETED}
  else throw new WorkflowError(422,'Unknown workflow action.');return this.commit(a,before,df,action,payload.remarks||'',oldValues,newValues);
 }
}
